# Generated by Django 3.1.7 on 2021-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('narrator', models.CharField(max_length=100, verbose_name='Narrator')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('uploaded_time', models.DateTimeField(auto_now=True, verbose_name='Uploaded time')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('host', models.CharField(max_length=100, verbose_name='Host')),
                ('participants', models.TextField(blank=True, null=True, verbose_name='Participants')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('uploaded_time', models.DateTimeField(auto_now=True, verbose_name='Uploaded time')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('uploaded_time', models.DateTimeField(auto_now=True, verbose_name='Uploaded time')),
            ],
        ),
    ]
